server:
  port: 8090


spring:
  application:
    name: eureka-gateway

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

zuul:
  routes:
    api-ribbon:
      path: /ribbon/*
      serviceId: eureka-discovery-ribbon
    api-feign:
      path: /feign/*
      serviceId: eureka-discovery-feign